[package]
name = "gg2-common"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
num_enum = "0.7.3"
thiserror = "1.0.63"
uuid = "1.10.0"
