[package]
name = "gg2-common"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bevy = { version = "0.14.1", default-features = false }
flate2 = "1.0.33"
hex = "0.4.3"
num_enum = "0.7.3"
serde = { version = "1.0.210", features = ["derive"] }
serde-hjson = { version = "1.0.0", default-features = false }
thiserror = "1.0.63"
uuid = "1.10.0"
