[workspace]
resolver = "2"
members = [
    "gg2-client", "gg2-common", "gg2-custom-client",
]

[workspace.package]
version = "0.1.0"
authors = [ "ThePinkHacker" ]
license = "GPL-3.0-or-later"
repository = "https://github.thepinkhacker.com/gang-garrison-rs"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
