use enum_iterator::Sequence;
use num_enum::{IntoPrimitive, TryFromPrimitive};

#[repr(u8)]
#[derive(Debug, Clone, Copy, TryFromPrimitive, IntoPrimitive, PartialEq, Eq, Sequence, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "snake_case"))]
pub enum ChatBubble {
    RedScout,
    RedPyro,
    RedSoldier,
    RedHeavy,
    RedDemoman,
    RedMedic,
    RedEngineer,
    RedSpy,
    RedSniper,
    Red,
    BluScout,
    BluPyro,
    BluSoldier,
    BluHeavy,
    BluDemoman,
    BluMedic,
    BluEngineer,
    BluSpy,
    BluSniper,
    Blu,
    Exclamation,
    Question,
    Angry,
    Cry,
    Smile,
    Joy,
    Sad,
    Sweat,
    Fear,
    Intel,
    Spy,
    Sentry,
    Trap,
    Pit,
    Uber,
    Explosion,
    ThumbsUp,
    Left,
    Right,
    Down,
    Up,
    Sword,
    Shield,
    Check,
    Stop,
    Heal,
    SuperBurst,
    Quote,
    Curly,
    Bomb,
    Bat,
    Money,
    HeadShot,
    Detonator,
    UberMench,
    YayMoney,
    KillingBabies,
    BloodOnMySuit,
    RocketMan,
    Glitch,
    BrokenSentry,
    EasterEgg,
}
