[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    # (Nightly) Make the current crate share its generic instantiations
    "-Zshare-generics=y",
    # Mold linker
    "-C", "link-arg=-fuse-ld=mold"
]

[env]
# Set the asset directory when game is ran with cargo
GG2_ASSET_ROOT = { value = "assets", relative = true, force = true }
