[package]
name = "gg2-custom-client"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
env_logger = "0.11.8"
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
pollster = "0.4.0"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
wgpu = "25.0.0"
winit = "0.30.9"
