[package]
name = "gg2-client"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gg2-common.workspace = true
