[package]
name = "gg2-client"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gg2-common = { path = "../gg2-common" }
