name: Cargo Build & Test

on: [ pull_request, push ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        toolchain:
          - nightly
        os: [ ubuntu-latest ]
    steps:
      - name: Install Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev mold
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
